#!/bin/sh

set -xeu

target_dir="${1}"
slskd_data="${2}"
logs_dir="/var/log/cerberus"
email_address="${DEST_EMAIL_ADDRESS}"
quarantine_dir="${QUARANTINE_DIR}"

mkdir -p "${logs_dir}"
mkdir -p "${quarantine_dir}"

file_to_scan_path="$(echo "${slskd_data}" | sed -n 's/^.*localDirectoryName:\(.*\),remoteDirectoryName.*$/\1/p')"
file_to_scan_name="$(basename "${file_to_scan_path}")"
log_file="${logs_dir}/${file_to_scan_name}_scan.log"

echo "Processing file ${file_to_scan_name}" > "${log_file}"
clamscan -ir --heuristic-alerts=yes --scan-archive=yes --max-filesize=2000M --max-scansize=2000M "${file_to_scan_path}" >> "${log_file}" || true

infected_files=$(cat "${log_file}" | sed -ne 's/^Infected files: //p')

echo "" >> "${log_file}"

if [ "${infected_files}" -gt 0 ]; then
  echo "Moving infected file ${file_to_scan_name} to ${quarantine_dir}" >> "${log_file}"
  mv "${file_to_scan_path}" "${quarantine_dir}"/

  mail -s "Virus detected in slskd file ${file_to_scan_name}" "${email_address}" < "${log_file}"
else
  echo "File ${file_to_scan_name} is clean" >> "${log_file}"
  mail -s "slskd completed file ${file_to_scan_name}" "${email_address}" < "${log_file}"
  mv "${file_to_scan_path}" "${target_dir}"/
fi

echo "Email sent to ${email_address}" >> "${log_file}"
